import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header'
import Footer from '../../components/footer'
import ProductList from "../../components/productList"
import { IProduct } from "../../components/product"
import Contact from '../../components/contact'

import styles from '../../styles/Home.module.css'



const Custom = () => {
  return (
    <div className='app'>
      <Head>
        <title>Perception Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css" />
        <script async src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js"></script>
        <div id="snipcart" data-config-modal-style="side" data-api-key="Nzk3ZWRhZTMtNzJhNS00YWM5LWI1NTYtYjBiYjJjYjVhOWM0NjM3NTcxODU2MzQ1MjE3ODU0" hidden></div>
      </Head>

      <Header />

      <main className='main'>

        <div className='promotional-message'>
          {/* <h1>PERCEPTION ZERO</h1> */}
          {/* <h2>luxury streetwear</h2> */}
          <h2>Perceptiøn Zerø</h2>
          <h3>luxury streetwear</h3>
          <br></br>
          <br></br>
          <h4>happiness comes from within</h4>

        </div>
        
        {/* <ProductList products = {props.products} /> */}

        {/* <Contact /> */}

      </main>

      <Footer />
    </div>
  )
}



export default Custom

