import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/header'
import Footer from '../components/footer'
import ProductList from "../components/productList"
import { IProduct } from "../components/product"
import Contact from '../components/contact'

import styles from '../styles/Home.module.css'


interface IIndexProps {
  products: IProduct[]
}

const Home = (props: IIndexProps) => {
  return (
    <div className='app'>
      <Head>
        <title>Perception Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css" />
        <script async src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js"></script>
        <div id="snipcart" data-config-modal-style="side" data-api-key="Nzk3ZWRhZTMtNzJhNS00YWM5LWI1NTYtYjBiYjJjYjVhOWM0NjM3NTcxODU2MzQ1MjE3ODU0" hidden></div>
      </Head>

      <Header />

      <main className='main'>

        <div className='promotional-message'>
          {/* <h1>PERCEPTION ZERO</h1> */}
          {/* <h2>luxury streetwear</h2> */}
          <h2>Perceptiøn Zerø</h2>
          <h3>luxury streetwear</h3>
          <br></br>
          <br></br>
          <h4>happiness comes from within</h4>

        </div>
        
        <ProductList products = {props.products} />

        <Contact />

      </main>

      <Footer />
    </div>
  )
}


Home.getInitialProps = async () => {
  return {
    products: [
      // {id: "nextjs_halfmoon", name: "Halfmoon Betta", price: 25.00, image: "../static/halfmoon.jpg", description: "The Halfmoon betta is arguably one of the prettiest betta species. It is recognized by its large tail that can flare up to 180 degrees."} as IProduct,
      // {id: "nextjs_dragonscale", name: "Dragon Scale Betta", price: 35, image: "../static/dragonscale.jpg",description: "The dragon scale betta is a rarer and higher maintenance fish. It is named by its thick white scales covering his sides that looks like dragon scale armor."} as IProduct,
      // {id: "nextjs_crowntail", name: "Crowntail Betta", price: 7.50, image: "../static/crowntail.jpg", description: "The crowntail is pretty common, but interesting none the less. It's recognized by the shape of its tail that has an appearance of a comb."} as IProduct,
      // 
      
      // {
      //   id: "nextjs_veiltail", 
      //   name: "Veiltail Betta", 
      //   price: 5.00, 
      //   image: "../static/veiltail.jpg", 
      //   description: "By far the most common betta fish. You can recognize it by its long tail aiming downwards."
      // } as IProduct,

      {
        id: 'rockstar_denim', 
        name: 'Rockstar Denim', 
        price: 420.00, 
        image: '../public/images/Rockstar Denim.webp', 
        description: 'cool ass jeans. buy them please.', 
        url: '/products/rockstar'
      } as IProduct,
      {
        id: 'blood_wash_denim', 
        name: 'Blood Wash Denim', 
        price: 69.00, 
        image: '../public/images/Blood Wash Denim 3.webp', 
        description: 'cooler asser jeanser. pretty please buy these.',
        url: '/products/blood-wash'
      } as IProduct,
      {
        id: 'nightmare_denim', 
        name: 'Blood Wash Denim', 
        price: 321.00, 
        image: '../public/images/Nightmare Denim 1.webp', 
        description: 'cooler asser jeanser. pretty please buy these.',
        url: '/products/nightmare'
      } as IProduct,
      {
        id: 'jacket', 
        name: 'Jacket', 
        price: 800.85, 
        image: '../public/images/Jacket 1.jpg', 
        description: 'cooler asser jackettt. pretty please buy these.',
        url: '/products/jacket'
      } as IProduct,
    ]
  }
}

export default Home

