import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/header'
import Footer from '../components/footer'
import ProductList from "../components/productList"
import { IProduct } from "../components/product"

import styles from '../styles/Home.module.css'


interface IIndexProps {
  products: IProduct[]
}

const Home = (props: IIndexProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Perception Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        
      </Head>

      <Header />

      <main className={styles.main}>

        <div 
          className={styles.beginningText}
        >

          <h1 className={styles.title}>
            Perception Zero
          </h1>

        </div>
        
        <div className={styles.grid}>

          <Link href="/" className={styles.card} passHref >
            <a>
              <h2>Jeans &rarr;</h2>
            </a>
            
          </Link>
          

          <Link href="/" className={styles.card} passHref >
            <h2>Jackets &rarr;</h2>
          </Link>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
            
        </div>

      </main>

      <Footer />
    </div>
  )
}


Home.getInitialProps = async () => {
  return {
    products: [
      {id: "nextjs_halfmoon", name: "Halfmoon Betta", price: 25.00, image: "../static/halfmoon.jpg", description: "The Halfmoon betta is arguably one of the prettiest betta species. It is recognized by its large tail that can flare up to 180 degrees."} as IProduct,
      {id: "nextjs_dragonscale", name: "Dragon Scale Betta", price: 35, image: "../static/dragonscale.jpg",description: "The dragon scale betta is a rarer and higher maintenance fish. It is named by its thick white scales covering his sides that looks like dragon scale armor."} as IProduct,
      {id: "nextjs_crowntail", name: "Crowntail Betta", price: 7.50, image: "../static/crowntail.jpg", description: "The crowntail is pretty common, but interesting none the less. It's recognized by the shape of its tail that has an appearance of a comb."} as IProduct,
      {id: "nextjs_veiltail", name: "Veiltail Betta", price: 5.00, image: "../static/veiltail.jpg", description: "By far the most common betta fish. You can recognize it by its long tail aiming downwards."} as IProduct,
    ]
  }
}

export default Home