import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import Header from '../components/header'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Perception Zero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC&display=swap" rel="stylesheet" /> 

      </Head>

      <Header />

      <main className={styles.main}>

        <div 
          className={styles.beginningText}
        >

          <h1 className={styles.title}>
            Perception Zero
          </h1>

          
        </div>

      

        {/* <Image 
          src="/../public/images/Rockstar Denim.webp"
          width="100"
          height="100"
          alt="homepage image"
        /> */}
        
{/*
        <div className={styles.grid} style={{display: none,}}>

          
            
          
          <Link href="/" className={styles.card} passHref >
            <a>
              <h2>Jeans &rarr;</h2>
            </a>
            
          </Link>
          

          <Link href="/" className={styles.card} passHref >
            <h2>Jackets &rarr;</h2>
          </Link>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
            
        </div> */}
{/* asdf */}
      </main>

      <Footer />
    </div>
  )
}
